crew_test("relay wait_condition() timeout condition", {
  x <- crew_relay()
  x$start()
  cv <- nanonext::cv()
  x$from(cv)
  time <- system.time(x$wait_condition(seconds_timeout = 2))
  expect_gt(time["elapsed"], 1)
  expect_equal(nanonext::cv_value(x$condition), 0L)
  expect_equal(x$unpopped, 0L)
  expect_equal(x$popped, 0L)
  nanonext::cv_signal(x$condition)
  nanonext::msleep(250)
  expect_equal(nanonext::cv_value(x$condition), 1L)
  time <- system.time(x$wait_condition(seconds_timeout = 2))
  expect_lt(time["elapsed"], 1)
  expect_equal(nanonext::cv_value(x$condition), 0L)
  expect_equal(x$unpopped, 1L)
  expect_equal(x$popped, 0L)
})

crew_test("relay wait_condition() timeout unpopped", {
  x <- crew_relay()
  x$start()
  time <- system.time(x$wait_condition(seconds_timeout = 2))
  expect_gt(time["elapsed"], 1)
  expect_equal(nanonext::cv_value(x$condition), 0L)
  expect_equal(x$unpopped, 0L)
  expect_equal(x$popped, 0L)
  x$unpopped <- 1L
  time <- system.time(x$wait_condition(seconds_timeout = 2))
  expect_gt(time["elapsed"], 1)
  expect_equal(nanonext::cv_value(x$condition), 0L)
  expect_equal(x$unpopped, 1L)
  expect_equal(x$popped, 0L)
})

crew_test("relay wait_condition() timeout popped", {
  x <- crew_relay()
  x$start()
  time <- system.time(x$wait_condition(seconds_timeout = 2))
  expect_gt(time["elapsed"], 1)
  expect_equal(nanonext::cv_value(x$condition), 0L)
  expect_equal(x$unpopped, 0L)
  expect_equal(x$popped, 0L)
  x$popped <- 1L
  time <- system.time(x$wait_condition(seconds_timeout = 2))
  expect_gt(time["elapsed"], 1)
  expect_equal(nanonext::cv_value(x$condition), 0L)
  expect_equal(x$unpopped, 0L)
  expect_equal(x$popped, 1L)
})

crew_test("relay wait_unpopped() timeout condition", {
  x <- crew_relay()
  x$start()
  cv <- nanonext::cv()
  x$from(cv)
  time <- system.time(x$wait_unpopped(seconds_timeout = 2))
  expect_gt(time["elapsed"], 1)
  expect_equal(nanonext::cv_value(x$condition), 0L)
  expect_equal(x$unpopped, 0L)
  expect_equal(x$popped, 0L)
  nanonext::cv_signal(x$condition)
  nanonext::msleep(250)
  expect_equal(nanonext::cv_value(x$condition), 1L)
  time <- system.time(x$wait_unpopped(seconds_timeout = 2))
  expect_lt(time["elapsed"], 1)
  expect_equal(nanonext::cv_value(x$condition), 0L)
  expect_equal(x$unpopped, 1L)
  expect_equal(x$popped, 0L)
})

crew_test("relay wait_unpopped() timeout unpopped", {
  x <- crew_relay()
  x$start()
  time <- system.time(x$wait_unpopped(seconds_timeout = 2))
  expect_gt(time["elapsed"], 1)
  expect_equal(nanonext::cv_value(x$condition), 0L)
  expect_equal(x$unpopped, 0L)
  expect_equal(x$popped, 0L)
  x$unpopped <- 1L
  time <- system.time(x$wait_unpopped(seconds_timeout = 2))
  expect_lt(time["elapsed"], 1)
  expect_equal(nanonext::cv_value(x$condition), 0L)
  expect_equal(x$unpopped, 1L)
  expect_equal(x$popped, 0L)
})

crew_test("relay wait_unpopped() timeout popped", {
  x <- crew_relay()
  x$start()
  time <- system.time(x$wait_unpopped(seconds_timeout = 2))
  expect_gt(time["elapsed"], 1)
  expect_equal(nanonext::cv_value(x$condition), 0L)
  expect_equal(x$unpopped, 0L)
  expect_equal(x$popped, 0L)
  x$popped <- 1L
  time <- system.time(x$wait_unpopped(seconds_timeout = 2))
  expect_gt(time["elapsed"], 1)
  expect_equal(nanonext::cv_value(x$condition), 0L)
  expect_equal(x$unpopped, 0L)
  expect_equal(x$popped, 1L)
})

crew_test("relay wait_resolved() timeout condition", {
  x <- crew_relay()
  x$start()
  cv <- nanonext::cv()
  x$from(cv)
  time <- system.time(x$wait_resolved(seconds_timeout = 2, resolved = 1L))
  expect_gt(time["elapsed"], 1)
  expect_equal(nanonext::cv_value(x$condition), 0L)
  expect_equal(x$unpopped, 0L)
  expect_equal(x$popped, 0L)
  nanonext::cv_signal(x$condition)
  nanonext::msleep(250)
  expect_equal(nanonext::cv_value(x$condition), 1L)
  time <- system.time(x$wait_resolved(seconds_timeout = 2, resolved = 1L))
  expect_lt(time["elapsed"], 1)
  expect_equal(nanonext::cv_value(x$condition), 1L)
  expect_equal(x$unpopped, 0L)
  expect_equal(x$popped, 0L)
})

crew_test("relay wait_resolved() timeout unpopped", {
  x <- crew_relay()
  x$start()
  time <- system.time(x$wait_resolved(seconds_timeout = 2, resolved = 1L))
  expect_gt(time["elapsed"], 1)
  expect_equal(nanonext::cv_value(x$condition), 0L)
  expect_equal(x$unpopped, 0L)
  expect_equal(x$popped, 0L)
  x$unpopped <- 1L
  time <- system.time(x$wait_resolved(seconds_timeout = 2, resolved = 1L))
  expect_lt(time["elapsed"], 1)
  expect_equal(nanonext::cv_value(x$condition), 0L)
  expect_equal(x$unpopped, 1L)
  expect_equal(x$popped, 0L)
})

crew_test("relay wait_resolved() timeout popped", {
  x <- crew_relay()
  x$start()
  time <- system.time(x$wait_resolved(seconds_timeout = 2, resolved = 1L))
  expect_gt(time["elapsed"], 1)
  expect_equal(nanonext::cv_value(x$condition), 0L)
  expect_equal(x$unpopped, 0L)
  expect_equal(x$popped, 0L)
  x$popped <- 1L
  time <- system.time(x$wait_resolved(seconds_timeout = 2, resolved = 1L))
  expect_lt(time["elapsed"], 1)
  expect_equal(nanonext::cv_value(x$condition), 0L)
  expect_equal(x$unpopped, 0L)
  expect_equal(x$popped, 1L)
})
