crew_test("stage wait_unobserved() with timeouts", {
  x <- crew_stage()
  x$start()
  cv <- nanonext::cv()
  x$inherit(cv)
  time <- system.time(x$wait_unobserved(milliseconds_timeout = 2000))
  expect_gt(time["elapsed"], 1)
  expect_equal(nanonext::cv_value(x$condition), 0L)
  expect_equal(x$unpopped, 0L)
  expect_equal(x$popped, 0L)
  nanonext::cv_signal(x$condition)
  expect_equal(nanonext::cv_value(x$condition), 1L)
  time <- system.time(x$wait_unobserved(milliseconds_timeout = 2000))
  expect_lt(time["elapsed"], 1)
  expect_equal(nanonext::cv_value(x$condition), 0L)
  expect_equal(x$unpopped, 1L)
  expect_equal(x$popped, 0L)
})
