crew_test("crew_controller_callr()", {
  x <- crew_controller_callr(idle_time = 360)
  on.exit(x$terminate())
  expect_silent(x$validate())
  expect_false(x$router$is_connected())
  x$connect()
  x$push(command = ps::ps_pid(), name = "task_pid")
  x$wait(timeout = 5)
  out <- x$pop()
  expect_equal(out$name, "task_pid")
  expect_equal(out$command, "ps::ps_pid()")
  expect_equal(out$result[[1]], x$launcher$workers[[1]]$get_pid())
  expect_true(is.numeric(out$seconds))
  expect_false(anyNA(out$seconds))
  expect_true(out$seconds >= 0)
  expect_true(anyNA(out$error))
  expect_true(anyNA(out$traceback))
  expect_true(anyNA(out$warnings))
  x$terminate()
  expect_false(x$router$is_connected())
  expect_equal(x$launcher$running(), 0L)
})

crew_test("crew_controller_callr() warnings and errors", {
  skip_on_cran()
  x <- crew_controller_callr(idle_time = 360)
  on.exit(x$terminate())
  expect_silent(x$validate())
  expect_false(x$router$is_connected())
  x$connect()
  x$push(command = ps::ps_pid(), name = "task_pid")
  x$wait(timeout = 5)
  out <- x$pop()
  expect_equal(out$name, "task_pid")
  expect_equal(out$command, "ps::ps_pid()")
  expect_equal(out$result[[1]], x$launcher$workers[[1]]$get_pid())
  expect_true(is.numeric(out$seconds))
  expect_false(anyNA(out$seconds))
  expect_true(out$seconds >= 0)
  expect_true(anyNA(out$error))
  expect_true(anyNA(out$traceback))
  expect_true(anyNA(out$warnings))
  x$terminate()
  expect_false(x$router$is_connected())
  expect_equal(x$launcher$running(), 0L)
})

crew_test("crew_controller_callr() launch method", {
  skip_on_cran()
  x <- crew_controller_callr(idle_time = 360)
  on.exit(x$terminate())
  x$connect()
  expect_equal(x$launcher$running(), 0L)
  x$launch(n = 1L)
  expect_equal(x$launcher$running(), 1L)
  x$terminate()
  expect_equal(x$launcher$running(), 0L)
})
