crew_test("worker input", {
  x <- crew_store_local$new()
  expect_false(x$exists_worker_input("worker"))
  expect_equal(x$list_worker_input(), character(0))
  x$write_worker_input("worker", value = "x")
  expect_true(x$exists_worker_input("worker"))
  expect_equal(x$list_worker_input(), "worker")
  expect_equal(x$read_worker_input("worker"), "x")
  x$delete_worker_input("worker")
  expect_false(x$exists_worker_input("worker"))
})

crew_test("worker output", {
  x <- crew_store_local$new()
  expect_false(x$exists_worker_output("worker"))
  expect_equal(x$list_worker_output(), character(0))
  x$write_worker_output("worker", value = "x")
  expect_true(x$exists_worker_output("worker"))
  expect_equal(x$list_worker_output(), "worker")
  expect_equal(x$read_worker_output("worker"), "x")
  x$delete_worker_output("worker")
  expect_false(x$exists_worker_output("worker"))
})

crew_test("worker error", {
  x <- crew_store_local$new()
  expect_false(x$exists_worker_error("worker"))
  expect_equal(x$list_worker_error(), character(0))
  x$write_worker_error("worker", value = "x")
  expect_true(x$exists_worker_error("worker"))
  expect_equal(x$list_worker_error(), "worker")
  expect_equal(x$read_worker_error("worker"), "x")
  x$delete_worker_error("worker")
  expect_false(x$exists_worker_error("worker"))
})

crew_test("upload input", {
  x <- crew_store_local$new()
  x$write_main_input("worker", value = "x")
  expect_true(x$exists_main_input("worker"))
  expect_false(x$exists_worker_input("worker"))
  x$upload_input("worker")
  expect_false(x$exists_main_input("worker"))
  expect_true(x$exists_worker_input("worker"))
})

crew_test("download output", {
  x <- crew_store_local$new()
  x$write_worker_output("worker", value = "x")
  expect_true(x$exists_worker_output("worker"))
  expect_false(x$exists_main_output("worker"))
  x$download_output("worker")
  expect_false(x$exists_worker_output("worker"))
  expect_true(x$exists_main_output("worker"))
})

crew_test("marshal", {
  x <- crew_store_local$new()
  out <- x$marshal()
  expect_true(is.character(out) && length(out) == 1L && nzchar(out))
  y <- eval(parse(text = out))
  expect_equal(class(x), class(y))
  expect_equal(x$get_root(), y$get_root())
})
