crew_test("dir_create()", {
  skip_on_cran()
  dir <- tempfile()
  on.exit(unlink(dir, recursive = TRUE))
  tmp <- file.path(dir, "x", "y")
  expect_false(dir.exists(tmp))
  expect_false(file.exists(tmp))
  dir_create(tmp)
  expect_true(dir.exists(tmp))
  expect_true(file.exists(tmp))
  expect_silent(dir_create(tmp))
})
