test_that("temp path", {
  x <- class_store_local$new()
  expect_equal(x$path_temp("abc"), file.path(x$dir_root, "temp", "abc"))
})

test_that("local store input", {
  x <- class_store_local$new()
  name <- "abc"
  data <- list(x = "x")
  expect_false(file.exists(x$path_input(name)))
  expect_false(x$exists_input(name))
  expect_error(x$read_input(name), class = "crew_error")
  x$write_input(name, data)
  expect_true(file.exists(x$path_input(name)))
  expect_true(x$exists_input(name))
  expect_equal(x$read_input(name), data)
  x$delete_input(name)
  expect_true(file.exists(x$dir_root))
  expect_false(file.exists(x$path_input(name)))
  expect_false(x$exists_input(name))
  x$destroy()
  expect_false(file.exists(x$dir_root))
})

test_that("local store output", {
  x <- class_store_local$new()
  name <- "abc"
  data <- list(x = "x")
  expect_false(file.exists(x$path_output(name)))
  expect_false(x$exists_output(name))
  expect_error(x$read_output(name), class = "crew_error")
  x$write_output(name, data)
  expect_true(file.exists(x$path_output(name)))
  expect_true(x$exists_output(name))
  expect_equal(x$read_output(name), data)
  x$delete_output(name)
  expect_true(file.exists(x$dir_root))
  expect_false(file.exists(x$path_output(name)))
  expect_false(x$exists_output(name))
  x$destroy()
  expect_false(file.exists(x$dir_root))
})
